<a href="https://colab.research.google.com/github/SanGyuk-Raccoon/DACON_1/blob/main/Pytorch_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
x = torch.empty(3, 4)
print(x)

tensor([[8.2426e+05, 3.0667e-41, 3.3631e-44, 0.0000e+00],
        [       nan, 6.4460e-44, 1.1578e+27, 1.1362e+30],
        [7.1547e+22, 4.5828e+30, 1.2121e+04, 7.1846e+22]])


In [3]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.zeros(2)

tensor([0., 0.])

In [8]:
torch.rand(5, 6)

tensor([[0.1282, 0.6502, 0.4181, 0.7074, 0.2650, 0.3776],
        [0.9111, 0.7152, 0.6340, 0.4744, 0.4897, 0.8755],
        [0.7681, 0.0067, 0.0835, 0.5679, 0.4589, 0.3635],
        [0.2270, 0.3942, 0.0844, 0.0412, 0.0628, 0.0812],
        [0.3613, 0.6649, 0.0756, 0.7559, 0.3080, 0.9932]])

In [9]:
lst = [1, 2, 3]
arr = np.array([1, 2, 3])

In [10]:
lst

[1, 2, 3]

In [11]:
arr

array([1, 2, 3])

In [12]:
torch.tensor(lst)

tensor([1, 2, 3])

In [13]:
torch.tensor(arr)

tensor([1, 2, 3])

In [14]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)

print(x)
print(y)

tensor([[0.1884, 0.2952],
        [0.0934, 0.2587]])
tensor([[0.9203, 0.5621],
        [0.4505, 0.4203]])


In [15]:
x + y

tensor([[1.1087, 0.8573],
        [0.5439, 0.6790]])

In [16]:
torch.add(x, y)

tensor([[1.1087, 0.8573],
        [0.5439, 0.6790]])

In [17]:
y.add(x)

tensor([[1.1087, 0.8573],
        [0.5439, 0.6790]])

In [18]:
x.add(y)

tensor([[1.1087, 0.8573],
        [0.5439, 0.6790]])

In [19]:
y.add_(x) # 더한 값으로 업데이트함

tensor([[1.1087, 0.8573],
        [0.5439, 0.6790]])

In [20]:
# 인덱스 슬라이싱
y[:, 1]

tensor([0.8573, 0.6790])

In [21]:
x = torch.rand(8, 8)
print(x)

tensor([[0.0214, 0.5172, 0.4655, 0.8817, 0.8821, 0.0023, 0.8226, 0.2263],
        [0.3134, 0.2173, 0.1538, 0.3809, 0.9850, 0.5018, 0.4293, 0.8909],
        [0.0140, 0.6238, 0.3258, 0.5183, 0.0056, 0.7205, 0.8230, 0.8128],
        [0.7496, 0.4634, 0.8310, 0.7676, 0.3391, 0.1441, 0.2929, 0.7896],
        [0.6677, 0.1086, 0.9356, 0.9506, 0.6686, 0.2363, 0.5484, 0.9522],
        [0.9497, 0.9434, 0.0513, 0.7363, 0.6676, 0.1738, 0.0121, 0.0133],
        [0.7569, 0.5398, 0.8727, 0.9783, 0.3996, 0.4072, 0.1508, 0.8894],
        [0.1582, 0.5791, 0.5157, 0.0488, 0.2638, 0.0184, 0.7902, 0.7430]])


In [23]:
x.view(64)

tensor([0.0214, 0.5172, 0.4655, 0.8817, 0.8821, 0.0023, 0.8226, 0.2263, 0.3134,
        0.2173, 0.1538, 0.3809, 0.9850, 0.5018, 0.4293, 0.8909, 0.0140, 0.6238,
        0.3258, 0.5183, 0.0056, 0.7205, 0.8230, 0.8128, 0.7496, 0.4634, 0.8310,
        0.7676, 0.3391, 0.1441, 0.2929, 0.7896, 0.6677, 0.1086, 0.9356, 0.9506,
        0.6686, 0.2363, 0.5484, 0.9522, 0.9497, 0.9434, 0.0513, 0.7363, 0.6676,
        0.1738, 0.0121, 0.0133, 0.7569, 0.5398, 0.8727, 0.9783, 0.3996, 0.4072,
        0.1508, 0.8894, 0.1582, 0.5791, 0.5157, 0.0488, 0.2638, 0.0184, 0.7902,
        0.7430])

In [24]:
x.view(4, 16)

tensor([[0.0214, 0.5172, 0.4655, 0.8817, 0.8821, 0.0023, 0.8226, 0.2263, 0.3134,
         0.2173, 0.1538, 0.3809, 0.9850, 0.5018, 0.4293, 0.8909],
        [0.0140, 0.6238, 0.3258, 0.5183, 0.0056, 0.7205, 0.8230, 0.8128, 0.7496,
         0.4634, 0.8310, 0.7676, 0.3391, 0.1441, 0.2929, 0.7896],
        [0.6677, 0.1086, 0.9356, 0.9506, 0.6686, 0.2363, 0.5484, 0.9522, 0.9497,
         0.9434, 0.0513, 0.7363, 0.6676, 0.1738, 0.0121, 0.0133],
        [0.7569, 0.5398, 0.8727, 0.9783, 0.3996, 0.4072, 0.1508, 0.8894, 0.1582,
         0.5791, 0.5157, 0.0488, 0.2638, 0.0184, 0.7902, 0.7430]])

In [25]:
x.view(-1, 16)

tensor([[0.0214, 0.5172, 0.4655, 0.8817, 0.8821, 0.0023, 0.8226, 0.2263, 0.3134,
         0.2173, 0.1538, 0.3809, 0.9850, 0.5018, 0.4293, 0.8909],
        [0.0140, 0.6238, 0.3258, 0.5183, 0.0056, 0.7205, 0.8230, 0.8128, 0.7496,
         0.4634, 0.8310, 0.7676, 0.3391, 0.1441, 0.2929, 0.7896],
        [0.6677, 0.1086, 0.9356, 0.9506, 0.6686, 0.2363, 0.5484, 0.9522, 0.9497,
         0.9434, 0.0513, 0.7363, 0.6676, 0.1738, 0.0121, 0.0133],
        [0.7569, 0.5398, 0.8727, 0.9783, 0.3996, 0.4072, 0.1508, 0.8894, 0.1582,
         0.5791, 0.5157, 0.0488, 0.2638, 0.0184, 0.7902, 0.7430]])

In [26]:
x.view(4, -1)

tensor([[0.0214, 0.5172, 0.4655, 0.8817, 0.8821, 0.0023, 0.8226, 0.2263, 0.3134,
         0.2173, 0.1538, 0.3809, 0.9850, 0.5018, 0.4293, 0.8909],
        [0.0140, 0.6238, 0.3258, 0.5183, 0.0056, 0.7205, 0.8230, 0.8128, 0.7496,
         0.4634, 0.8310, 0.7676, 0.3391, 0.1441, 0.2929, 0.7896],
        [0.6677, 0.1086, 0.9356, 0.9506, 0.6686, 0.2363, 0.5484, 0.9522, 0.9497,
         0.9434, 0.0513, 0.7363, 0.6676, 0.1738, 0.0121, 0.0133],
        [0.7569, 0.5398, 0.8727, 0.9783, 0.3996, 0.4072, 0.1508, 0.8894, 0.1582,
         0.5791, 0.5157, 0.0488, 0.2638, 0.0184, 0.7902, 0.7430]])

In [27]:
x.view(-1, 4, 4)

tensor([[[0.0214, 0.5172, 0.4655, 0.8817],
         [0.8821, 0.0023, 0.8226, 0.2263],
         [0.3134, 0.2173, 0.1538, 0.3809],
         [0.9850, 0.5018, 0.4293, 0.8909]],

        [[0.0140, 0.6238, 0.3258, 0.5183],
         [0.0056, 0.7205, 0.8230, 0.8128],
         [0.7496, 0.4634, 0.8310, 0.7676],
         [0.3391, 0.1441, 0.2929, 0.7896]],

        [[0.6677, 0.1086, 0.9356, 0.9506],
         [0.6686, 0.2363, 0.5484, 0.9522],
         [0.9497, 0.9434, 0.0513, 0.7363],
         [0.6676, 0.1738, 0.0121, 0.0133]],

        [[0.7569, 0.5398, 0.8727, 0.9783],
         [0.3996, 0.4072, 0.1508, 0.8894],
         [0.1582, 0.5791, 0.5157, 0.0488],
         [0.2638, 0.0184, 0.7902, 0.7430]]])

In [29]:
x.numpy()

array([[0.02141845, 0.51715904, 0.46551985, 0.8817026 , 0.8820751 ,
        0.00233251, 0.8225669 , 0.2263332 ],
       [0.31337595, 0.21731788, 0.15380448, 0.38089645, 0.9849589 ,
        0.5018125 , 0.42927235, 0.8908504 ],
       [0.01398444, 0.62376964, 0.32579452, 0.5182759 , 0.00559264,
        0.7204748 , 0.8230104 , 0.81282073],
       [0.7495815 , 0.46336138, 0.83103395, 0.7676118 , 0.33913237,
        0.14406121, 0.29289883, 0.7896227 ],
       [0.667685  , 0.10860628, 0.9355635 , 0.95058405, 0.6685946 ,
        0.23629874, 0.5484197 , 0.9522051 ],
       [0.9497337 , 0.9434418 , 0.05131221, 0.736344  , 0.66760993,
        0.17376983, 0.01206493, 0.01330286],
       [0.75693214, 0.53979886, 0.8727113 , 0.97834986, 0.39964074,
        0.40717393, 0.15076607, 0.8894081 ],
       [0.15815592, 0.5791118 , 0.51573986, 0.04875445, 0.26382715,
        0.01843643, 0.7902425 , 0.7430464 ]], dtype=float32)

In [31]:
x = torch.ones(1)
x

tensor([1.])

In [32]:
x.item()

1.0